"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import {
  Loader2,
  Sparkles,
  ArrowRight,
  Wrench,
  Zap,
  Home,
  Hammer,
  PaintBucket,
  Warehouse,
  Trees,
  Brush,
  Grid3X3,
  Key,
  Wrench as WrenchIcon,
  SprayCanIcon,
  Flower2,
  Bug,
  ThermometerSun,
} from "lucide-react";

interface Trade {
  slug: string;
  name: string;
  demo_business_name: string;
  demo_location: string;
}

const tradeIcons: Record<string, React.ReactNode> = {
  plumber: <Wrench className="w-8 h-8" />,
  electrician: <Zap className="w-8 h-8" />,
  builder: <Home className="w-8 h-8" />,
  carpenter: <Hammer className="w-8 h-8" />,
  painter: <PaintBucket className="w-8 h-8" />,
  roofer: <Warehouse className="w-8 h-8" />,
  landscaper: <Trees className="w-8 h-8" />,
  plasterer: <Brush className="w-8 h-8" />,
  tiler: <Grid3X3 className="w-8 h-8" />,
  locksmith: <Key className="w-8 h-8" />,
  handyman: <WrenchIcon className="w-8 h-8" />,
  cleaner: <SprayCanIcon className="w-8 h-8" />,
  gardener: <Flower2 className="w-8 h-8" />,
  "pest-control": <Bug className="w-8 h-8" />,
  hvac: <ThermometerSun className="w-8 h-8" />,
};

const tradeColors: Record<string, string> = {
  plumber: "#2563eb",
  electrician: "#f59e0b",
  builder: "#dc2626",
  carpenter: "#92400e",
  painter: "#7c3aed",
  roofer: "#0891b2",
  landscaper: "#15803d",
  plasterer: "#64748b",
  tiler: "#0d9488",
  locksmith: "#1e40af",
  handyman: "#ea580c",
  cleaner: "#0284c7",
  gardener: "#65a30d",
  "pest-control": "#4f46e5",
  hvac: "#dc2626",
};

export default function DemoIndexPage() {
  const [trades, setTrades] = useState<Trade[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchTrades();
  }, []);

  const fetchTrades = async () => {
    try {
      const response = await fetch("/api/demo/trades");
      const data = await response.json();
      setTrades(data.trades || []);
    } catch (error) {
      console.error("Failed to fetch trades:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-900">
      {/* Header */}
      <header className="border-b border-gray-800">
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-lg">T</span>
            </div>
            <span className="text-xl font-bold text-white">TradeVista</span>
          </Link>
          <Link
            href="/signup"
            className="px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700"
          >
            Build Your Site
          </Link>
        </div>
      </header>

      {/* Hero */}
      <section className="py-20 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600/20 text-blue-400 rounded-full mb-6">
            <Sparkles className="w-4 h-4" />
            <span className="text-sm font-medium">Demo Gallery</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-6">
            See What Your Site Could Look Like
          </h1>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto">
            Browse demo sites for different trades. Each one was generated by AI in under 60 seconds.
            Your site could look just as good.
          </p>
        </div>
      </section>

      {/* Trades Grid */}
      <section className="pb-20 px-4">
        <div className="max-w-7xl mx-auto">
          {loading ? (
            <div className="flex items-center justify-center py-20">
              <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
            </div>
          ) : (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {trades.map((trade) => (
                <Link
                  key={trade.slug}
                  href={`/demo/${trade.slug}`}
                  className="group bg-gray-800 rounded-xl p-6 border border-gray-700 hover:border-blue-500 transition-all hover:shadow-lg hover:shadow-blue-500/10"
                >
                  <div className="flex items-start gap-4">
                    <div
                      className="w-14 h-14 rounded-xl flex items-center justify-center text-white shrink-0"
                      style={{ backgroundColor: tradeColors[trade.slug] || "#3b82f6" }}
                    >
                      {tradeIcons[trade.slug] || <Wrench className="w-8 h-8" />}
                    </div>
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold text-white mb-1 group-hover:text-blue-400 transition-colors">
                        {trade.name}
                      </h3>
                      <p className="text-gray-400 text-sm mb-3">
                        {trade.demo_business_name} - {trade.demo_location}
                      </p>
                      <div className="flex items-center text-blue-400 text-sm font-medium">
                        View Demo
                        <ArrowRight className="w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform" />
                      </div>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-4 bg-gradient-to-br from-blue-600 to-purple-600">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
            Ready to Build Your Own?
          </h2>
          <p className="text-xl text-white/80 mb-10">
            Join TradeVista and get a professional website in under 60 seconds.
            No design skills needed.
          </p>
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 px-8 py-4 bg-white text-blue-600 rounded-full font-semibold text-lg hover:bg-gray-100 transition-colors"
          >
            <Sparkles className="w-5 h-5" />
            Start Building Free
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 px-4 border-t border-gray-800">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <p className="text-gray-500">&copy; {new Date().getFullYear()} TradeVista</p>
          <div className="flex gap-6">
            <Link href="/" className="text-gray-400 hover:text-white">
              Home
            </Link>
            <Link href="/signup" className="text-gray-400 hover:text-white">
              Sign Up
            </Link>
            <Link href="/login" className="text-gray-400 hover:text-white">
              Login
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
